# Generated by Django 3.0.2 on 2020-10-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listing_startingbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='startingbid',
            field=models.FloatField(default=0),
        ),
    ]
