# Generated by Django 3.0.2 on 2020-10-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201014_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
